### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by albertandking**
1. format pyproject.toml to run CI
2. add ignore E402 and tests fold

### CODE REVIEW

**Comment by albertandking** [comment]
Hi Ed,  I have tested it through github action CI, It will be fine now

**Review by edtechre — APPROVED** [review]
Thank you Albert!

**Comment by edtechre** [comment]
Hi Albert, it looks this causes the schedule run to fail for some reason. Any ideas? I will look into it.

**Comment by albertandking** [comment]
> Hi Albert, it looks this causes the schedule run to fail for some reason. Any ideas? I will look into it.

Hi Ed，I have just test it on my master branch of pybroker, but it runs fine. you can check my https://github.com/albertandking/pybroker/actions/runs/8532047906; can you rerun all actions?

**Comment by edtechre** [comment]
If you run "ruff src tests" it appears to fail. main.yml will only run ruff on src.

**Comment by edtechre** [comment]
Also, it would be good to run the ruff formatter on both tests and __init__.py

**Comment by albertandking** [comment]
> Also, it would be good to run the ruff formatter on both tests and **init**.py

yes, I have turn off ruff run on init and tests in pyproject.toml

**Comment by edtechre** [comment]
Added per-file-ignores to pyproject.toml

**Comment by albertandking** [comment]
> Added per-file-ignores to pyproject.toml

I have fix the schedule.yml the same as main.yml for ruff, it will be ok?

**Comment by edtechre** [comment]
Hi Albert, thanks, but I think I've fixed this.

**Pull request merged**
